version: "3.8"
services:
  dashapp:
    build: .
    ports:
      - "8050:8050"
    environment:
    - CAM_USER=${CAM_USER}
    - CAM_PWD=${CAM_PWD}
    - MEDIAMTX_SERVER_IP=${MEDIAMTX_SERVER_IP}
    - STREAM_NAME=${STREAM_NAME}
    - TARGET_IP=${TARGET_IP}

    volumes:
      - .:/app
    restart: unless-stopped
